import AuthProvider from '@/Context/AuthProvider'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './shared/Navbar/Navbar'
import Footer from './shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en" data-theme="light">

      <AuthProvider >
        <body className={inter.className}>
          <div className=''>
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </AuthProvider>

    </html>
  )
}